version: '3.8'

services:
  api:
    build: ./Direct-Monero-API
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - backend

  frontend:
    build:
      context: ./Direct-Monero-Frontend
      args:
        VITE_API_URL: ${API_URL}
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=${API_URL}
    depends_on:
      - api
    networks:
      - frontend


networks:
  frontend:
  backend:

volumes:
  mongo-data: